version: '3.8'

x-common: &commons
  deploy:
    resources:
      limits:
        cpus: '0.5'
        memory: 1G
  mem_swappiness: 0
  memswap_limit: 0
  healthcheck:
    interval: 30s
    timeout: 30s
    retries: 3
    start_period: 60s

services:
  app:
    <<: *commons
    image: collection-manager
    build: .
    ports:
      - 3000:3000
    volumes:
      - .:/usr/src/app # Maps the entire project directory to the /usr/src/app directory in the container
      - /usr/src/app/node_modules # Prevents the local node_modules folder from overwriting the one inside the container
    working_dir: /usr/src/app
    environment:
      - CHOKIDAR_USEPOLLING=true # Use polling method for file-watching, helps with hot-reloading issues inside Docker
    command: yarn dev # or npm run dev, depending on your setup
    healthcheck:
      test: ["CMD", "curl", "http://localhost:3000/xprnetwork"]
